<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\fp;

use Closure;

/**
 * Creates an indexed array using keys generated by a callback function.
 *
 * Returns a curried function that transforms an array into an associative array where
 * keys are derived from the keyMaker callback applied to each element. Unlike groupBy,
 * this function creates a one-to-one mapping where each key maps to a single value.
 * If duplicate keys are generated, later values overwrite earlier ones.
 *
 * ```php
 * $users = [
 *     ['id' => 1, 'name' => 'Alice', 'email' => 'alice@example.com'],
 *     ['id' => 2, 'name' => 'Bob', 'email' => 'bob@example.com'],
 *     ['id' => 3, 'name' => 'Charlie', 'email' => 'charlie@example.com'],
 * ];
 *
 * $indexById = indexBy(fn($user) => $user['id']);
 * $usersById = $indexById($users);
 * // [
 * //   1 => ['id' => 1, 'name' => 'Alice', ...],
 * //   2 => ['id' => 2, 'name' => 'Bob', ...],
 * //   3 => ['id' => 3, 'name' => 'Charlie', ...]
 * // ]
 * ```
 *
 * @param  callable                            $keyMaker Callback function receiving each value and returning the index key.
 *                                                       The returned key will be used as the array key for that element.
 * @return Closure(array): array<mixed, mixed> Returns a function accepting an array that produces
 *                                             an associative array indexed by the generated keys
 */
function indexBy(callable $keyMaker): Closure
{
    return static function (array $arr) use ($keyMaker): array {
        $ret = [];

        foreach ($arr as $v) {
            $ret[$keyMaker($v)] = $v;
        }

        return $ret;
    };
}
